name: Basic Workflow
on: [push]

jobs:
  k6_local_test:
    name: k6 local test run - basic example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: basic/script.js
          flags: --out json=output/results.json

      - name: Store performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-report
          path: output/results.json
